import type { Catalog, Metrics } from '../lib/types';
import { formatNumber, signed } from '../lib/presentation';
import { Icon } from './Icon';

export function DistrictTable({ metrics, catalog }: { metrics: Metrics; catalog: Catalog }) {
  return <section id="districts" className="panel district-table-panel" aria-labelledby="districts-title"><div className="panel-heading"><div><span className="eyebrow">РАВНОМЕРНОЕ РАЗВИТИЕ</span><h2 id="districts-title">Что меняется в районах</h2></div><span className="badge">5 районов</span></div><div className="table-scroll" tabIndex={0} role="region" aria-label="Сравнение районов, доступна горизонтальная прокрутка"><table><caption className="sr-only">Исходные и прогнозируемые оценки районов</caption><thead><tr><th scope="col">Район</th><th scope="col">Население</th><th scope="col">До</th><th scope="col">В сценарии</th><th scope="col">Изменение</th><th scope="col">Показатели ниже 40</th></tr></thead><tbody>{metrics.districts.map((district) => {
    const critical = metrics.critical_indicators.filter((item) => item.district_id === district.id);
    return <tr key={district.id}><th scope="row"><span className={`district-dot ${district.id}`}/>{district.name_ru}</th><td>{formatNumber(district.population_share * 100)}%</td><td>{formatNumber(district.baseline_score, 2)}</td><td><strong>{formatNumber(district.score, 2)}</strong></td><td><span className={district.delta > 0 ? 'positive' : district.delta < 0 ? 'negative' : 'muted'}>{signed(district.delta)}</span></td><td>{critical.length ? <span className="warning-badge">{critical.map((item) => `${item.indicator}: ${formatNumber(item.value, 1)}`).join(' · ')}</span> : <span className="safe-label"><Icon name="check" size={14}/>Нет</span>}</td></tr>;
  })}</tbody></table></div><details className="indicator-details"><summary>Все 10 показателей по районам<span>Шкала 0–100 · больше — лучше</span></summary><div className="table-scroll" tabIndex={0} role="region" aria-label="Все показатели, доступна горизонтальная прокрутка"><table><caption className="sr-only">Детальные показатели каждого района</caption><thead><tr><th scope="col">Район</th>{catalog.indicators.map((indicator) => <th scope="col" key={indicator.code}><abbr title={indicator.name_ru}>{indicator.code}</abbr></th>)}</tr></thead><tbody>{metrics.districts.map((district) => <tr key={district.id}><th scope="row">{district.name_ru}</th>{catalog.indicators.map((indicator) => <td key={indicator.code} className={district.indicators[indicator.code] < 40 ? 'negative' : ''}>{formatNumber(district.indicators[indicator.code], 1)}</td>)}</tr>)}</tbody></table></div><div className="indicator-legend">{catalog.indicators.map((indicator) => <span key={indicator.code}><strong>{indicator.code}</strong> {indicator.name_ru}</span>)}</div></details></section>;
}
